/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/index_deprecated`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useObtenerAgendas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useCrearAtencion`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ModalCrearAtencion`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/AgendarPaciente` | `/docente/AgendarPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/estudiante/AtenderPaciente` | `/estudiante/AtenderPaciente`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(auth)'}/docente/nuevaAtencion/[fichaId]` | `/docente/nuevaAtencion/[fichaId]`, params: Router.UnknownInputParams & { fichaId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/index_deprecated`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useObtenerAgendas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useCrearAtencion`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ModalCrearAtencion`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/docente/AgendarPaciente` | `/docente/AgendarPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/estudiante/AtenderPaciente` | `/estudiante/AtenderPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(auth)'}/docente/nuevaAtencion/[fichaId]` | `/docente/nuevaAtencion/[fichaId]`, params: Router.UnknownOutputParams & { fichaId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/index_deprecated${`?${string}` | `#${string}` | ''}` | `/../hooks/useObtenerAgendas${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/docente/HistorialMenu${`?${string}` | `#${string}` | ''}` | `/docente/HistorialMenu${`?${string}` | `#${string}` | ''}` | `/../hooks/useCrearAtencion${`?${string}` | `#${string}` | ''}` | `/../components/ModalCrearAtencion${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/docente/AgendarPaciente${`?${string}` | `#${string}` | ''}` | `/docente/AgendarPaciente${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/docente/CrearPaciente${`?${string}` | `#${string}` | ''}` | `/docente/CrearPaciente${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/estudiante/AtenderPaciente${`?${string}` | `#${string}` | ''}` | `/estudiante/AtenderPaciente${`?${string}` | `#${string}` | ''}` | `/screens/FichaMedicaActivaMenu${`?${string}` | `#${string}` | ''}` | `/screens/HistorialMenu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/index_deprecated`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useObtenerAgendas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useCrearAtencion`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ModalCrearAtencion`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/AgendarPaciente` | `/docente/AgendarPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/estudiante/AtenderPaciente` | `/estudiante/AtenderPaciente`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(auth)'}/docente/nuevaAtencion/${Router.SingleRoutePart<T>}` | `/docente/nuevaAtencion/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(auth)'}/docente/nuevaAtencion/[fichaId]` | `/docente/nuevaAtencion/[fichaId]`, params: Router.UnknownInputParams & { fichaId: string | number; } };
    }
  }
}
