/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/docente/CrearPaciente${`?${string}` | `#${string}` | ''}` | `/docente/CrearPaciente${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/docente/HistorialMenu${`?${string}` | `#${string}` | ''}` | `/docente/HistorialMenu${`?${string}` | `#${string}` | ''}` | `/screens/FichaMedicaActivaMenu${`?${string}` | `#${string}` | ''}` | `/screens/HistorialMenu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/CrearPaciente` | `/docente/CrearPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/docente/HistorialMenu` | `/docente/HistorialMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FichaMedicaActivaMenu`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HistorialMenu`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
